### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by guillaumedavidphd** [mmolero/efit2d-pyopencl#1]
Hello there,
Thanks a lot for your contribution! A documentation would be much appreciated. Some methods of the `EFIT2D` class are a bit obscure and would benefit from a short description.
Also I've been working on making this code compatible with Python 3 and solving some problems with scipy deprecations and the glumpy refactoring. The code runs fine on Python 3.7 at this point. I can make a PR if you're interested.
-G

**Comment by iturraran** [comment]
Dear Guillaume,
It is great that you managed to improved the EFIT2D!
What is a PR? You mean a GitHub repository with the
new version? I will be happy, I guess that Miguel too,
though I will have to ask him :)
Best regards,
        Ursula

**Comment by mmolero** [comment]
Thanks @guillaumedavidphd, of course if you have already tested your branch to be compatible with the latest versions of the used libraries, please make a PR. We would be happy to merge it. It is great you find this repo useful so that all your comments are really  appreciated. 

I recommend to make two PR: a) Related to add more docs, b) related to update code for compatibility. 



Thanks
